Solucion Reto #5
mouredev/retos-programacion-2023 pull request #1764
Opened 2023-02-03 19:24 UTC by SacrilegeTx

Solucion al reto #5

2023-02-03 23:35 UTC, joaquin-rivero commented
Buenas! Por favor revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios.

- El nombre de la PR debe ser Reto #[número] - [lenguaje/s]. En tu caso, en vez de los lenguajes pon "varios lenguajes" o algo así xD

2023-02-03 23:53 UTC, Roswell468 requested changes
Hola, por favor revisa tus cambios.
No puedes modificar el archivo **.gitignore**. Por favor, revierte ese cambio.

Gracias.
Saludos!

2023-02-04 01:32 UTC, SacrilegeTx commented
> Buenas! Por favor revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios.
> 
> * El nombre de la PR debe ser Reto #[número] - [lenguaje/s]. En tu caso, en vez de los lenguajes pon "varios lenguajes" o algo así xD

Corregido

> Hola, por favor revisa tus cambios. No puedes modificar el archivo **.gitignore**. Por favor, revierte ese cambio.
> 
> Gracias. Saludos!

Archivo eliminado, se ha colado cuando hice el pull.

2023-02-04 01:35 UTC, Roswell468 approved these changes

2023-02-04 01:35 UTC, Roswell468 commented
Gracias por participar!

2023-02-04 01:35 UTC, merged