Reto #5 - Kotlin, Swift, Javascript, HTML, Java, Octave, Haskell y Prolog
mouredev/retos-programacion-2023 pull request #1811
Opened 2023-02-05 21:53 UTC by jaimefere

## Describe tus cambios
***(Opcional)*** *Sobre todo aconsejable si la "Pull Request" se corresponde con una corrección adicional y no con la presentación de un ejercicio.*

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [ ] El título de mi Pull Request sigue este formato: "Reto #[número] - [lenguaje_utilizado]". *(Ej: Reto #0 - Kotlin")*
- [ ] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.kt)*
- [ ] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: Reto #0/kotlin/mouredev.kt)*
- [ ] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [ ] Únicamente he incluído los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/semanales2023](https://retosdeprogramacion.com/semanales2023).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2023-02-05 22:00 UTC, Roswell468 requested changes
Hola Jaime, tienes incluido un archivo de otro usuario en la PR. Por favor verifica los cambios.
Gracias.
Saludos!

2023-02-05 22:14 UTC, jaimefere commented
Acabo de hacer otro commit quitando el fichero de _gvielza_, no sé si así es suficiente.
Muchas gracias.
Saludos

2023-02-05 22:18 UTC, Roswell468 commented
Entiendo que no debería aparecer en la PR, aunque aparece como Deleted.
Creo que esto sería incorrecto porque al aprobarla borraría el file del otro usuario (aunque no soy experto en Git ☺️)

2023-02-06 09:56 UTC, Roswell468 requested changes
Entiendo que el file no debería aparecer en la PR, aunque sí aparece como Deleted.
Esto sería incorrecto porque al aprobarla borraría el file del otro usuario.
Por favor verifica tus cambios.

2023-02-06 15:09 UTC, Roswell468 requested changes
Hola Jaime, para poder aprobar tu PR necesitamos que no incluyas en la misma el file del otro usuario, ya que si la aprobamos como está actualmente borraría el file del usuario gvielza.
Por favor revierte esos cambios, o cierra esta PR y crea una nueva sólo con tus files.
Gracias!
Saludos!

2023-02-06 16:27 UTC, closed without merging