Create Go_799.js
mouredev/retos-programacion-2023 pull request #2538
Opened 2023-03-14 14:00 UTC by giovanyosorio

Reto Fizzbuzz javascript

## CAmbios
Function to print a fizzbuzz number

2023-03-14 20:57 UTC, giovanyosorio commented
programa que reciba un texto y transforme lenguaje natural a
 * "lenguaje hacker"

2023-03-14 21:12 UTC, giovanyosorio commented
Saludos cambio del archivo confirmado

2023-03-15 11:35 UTC, Roswell468 requested changes
Hola, la solución del reto 1 tiene nombre de fichero incorrecto.
Gracias.
Saludos.

2023-03-15 20:40 UTC, giovanyosorio commented
Hola, Ya cambien el nombre del archivo para el Reto #1 Js

Para los proximos archivos ya tengo el nombre asociado a mi usuario en GitHub mas la extension del lenguaje que use

Saludos

2023-03-16 11:59 UTC, Roswell468 approved these changes

2023-03-16 11:59 UTC, merged