Add files via upload
mouredev/retos-programacion-2023 pull request #3005
Opened 2023-04-12 16:10 UTC by JesusAlbornoz29

## Describe tus cambios
***(Opcional)*** *Sobre todo aconsejable si la "Pull Request" se corresponde con una corrección adicional y no con la presentación de un ejercicio.*

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [ ] El título de mi Pull Request sigue este formato: "Reto #[número] - [lenguaje_utilizado]". *(Ej: Reto #0 - Kotlin")*
- [ ] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.kt)*
- [ ] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: Reto #0/kotlin/mouredev.kt)*
- [ ] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [ ] Únicamente he incluído los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/semanales2023](https://retosdeprogramacion.com/semanales2023).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2023-04-12 16:40 UTC, JesusAlbornoz29 commented
Le dejo los hola mundo de los lenguajes que me parecen interesantes para su corrección y/o aprobación

2023-04-12 16:47 UTC, JesusAlbornoz29 commented
Aqui agregue el Reto #6 - PIEDRA, PAPEL, TIJERA, LAGARTO, SPOCK [Media]/python/JesusAlbornoz29.py
Pero no se si le aparece a usted

2023-04-12 22:22 UTC, Roswell468 requested changes
Hola, por favor revisa la PR.
Hay un archivo correspondiente al reto 4 que no se encuentra en la carpeta correspondiente.

![image](https://user-images.githubusercontent.com/88008233/231598980-e846c9a0-f4f4-4079-8dc1-92a968ee64dc.png)

Con respecto al reto 6, no lo veo en esta PR, pero revisando el repo ya está en la carpeta correspondiente (aprobado en una PR anterior).

Gracias.
Saludos.

2023-04-13 00:31 UTC, JesusAlbornoz29 commented
Eliminado el archivo que no correspondia.

2023-04-13 09:09 UTC, merged