Reto #15 - Python
mouredev/retos-programacion-2023 pull request #3113
Opened 2023-04-18 20:24 UTC by Majinka10

2023-04-19 10:52 UTC, Roswell468 requested changes
Hola! Por favor revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios.

El nombre el fichero debe coincidir con el de tu usuario en GitHub más la extensión del lenguaje. (Ej: mouredev.kt)

Gracias.
Saludos.

2023-04-21 18:32 UTC, Majinka10 commented
Ya realicé el cambio de nombre. Tuve algunos problemas al sincronizar el repositorio, pero ya están totalmente sincronizados y sin problemas de integridad.

2023-04-21 18:33 UTC, Majinka10 reviewed
Nombre actualizado.

2023-04-21 22:38 UTC, Roswell468 requested changes
Hola, vuelve a revisar la PR. Ahora hay 13 archivos adicionales de otros usuarios.
Gracias.
Saludos.

2023-04-24 00:00 UTC, closed without merging