Reto #17 - Dart
mouredev/retos-programacion-2023 pull request #3276
Opened 2023-04-29 16:36 UTC by titoworlddev

2023-04-29 17:51 UTC, Roswell468 reviewed
Hola, la carpeta del lenguaje con el archivo con tu solución debe encontrarse en la carpeta correspondiente al reto.

![image](https://user-images.githubusercontent.com/88008233/235316940-aaf771f2-c386-47d8-a81b-f24f10d15b75.png)

Por favor actualiza tus cambios.
Gracias.
Saludos.

2023-04-30 14:45 UTC, Roswell468 requested changes
Hola, la carpeta del lenguaje con el archivo con tu solución debe encontrarse en la carpeta correspondiente al reto.

![image](https://user-images.githubusercontent.com/88008233/235359308-bb76bca5-8e8d-4008-ae16-57409c0c2139.png)

Por favor revisa y actualiza tus cambios.
Gracias.
Saludos

2023-04-30 17:36 UTC, titoworlddev commented
Hola, disculpas, no me di cuenta. Ya deberia de estar arreglado

2023-05-01 13:02 UTC, Roswell468 approved these changes

2023-05-01 13:02 UTC, merged