Reto #27: Cuenta atrás -Rust
mouredev/retos-programacion-2023 pull request #3991
Opened 2023-07-03 20:27 UTC by CharlyEstudio

## Describe tus cambios
Para esta solución implemente un comando, esto, para empezar a integrar los retos que vengan a futuro, de esta forma, ir actualizando mi centro de soluciones.

Es importante que la ejecución se haga donde se encuentre el archivo 'retos.exe', se creo así por mi SO que tengo; si se requiere un comando para linux/mac, solo hay que ejecutar el comando:
```bash
$ cargo build --release
```

En el sistema operativo que se requiera y se genera en la carpeta: ./target/releases/retos. En este caso, se renombro a mouredev por los requerimientos del PR, al crearlo, se puede usar como retos decrementar tiempo 10 2 o si se renombra como biene los comandos de abajo.

### Comandos
```bash
# Ayuda para comando principal
$ mouredev --help

# Ayuda para comando decrementar
$ mouredev decrementar --help

# Ayuda para subcomando de decrementar, en este caso tiempo
$ mouredev decrementar tiempo --help

# Ejecutar Reto 27
$ mouredev decrementar tiempo <comienza> <segundos>
$ mouredev decrementar tiempo 10 2
```

### Modo Desarrollo
```bash
# Ingresar a la carpeta code y ejecutar
$ cargo run -- --help

# Probar Decrementar
cargo run decrementar --help
cargo run decrementar tiempo --help
cargo run decrementar tiempo 10 2
```

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [x] El título de mi Pull Request sigue este formato: "Reto #[número] - [lenguaje_utilizado]". *(Ej: Reto #0 - Kotlin")*
- [x] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.kt)*
- [x] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: Reto #0/kotlin/mouredev.kt)*
- [x] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [x] Únicamente he incluído los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/semanales2023](https://retosdeprogramacion.com/semanales2023).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2023-07-03 23:07 UTC, Roswell468 requested changes
Hola! Por favor revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios.

- No se aceptarán PRs con archivos adicionales.
- La solución debe estar en un único fichero, dentro de la carpeta del lenguaje correspondiente, y el nombre del fichero debe coincidir con el de tu usuario en GitHub más la extensión del lenguaje. (Ej: mouredev.kt)

Gracias.
Saludos.

2023-07-03 23:38 UTC, CharlyEstudio commented
Crei que se tenia que enviar todo el proyecto! Sorry, mando como se requiere. Saludos y gracias por el feedback!

2023-07-03 23:44 UTC, Roswell468 requested changes
Vuelve a revisar tus cambios.
- No puedes eliminar el archivo ejercicio.md. Por favor revierte ese cambio.
- El fichero debe coincidir con tu nombre de usuario de GitHub.

Gracias.
Saludos.

2023-07-04 00:02 UTC, CharlyEstudio commented
Puff una disculpa, es mi primer PR con Mouredev, una vez que le agarre la onda ya mi ire fino! Va los cambios, sorry! Gracias y saludos!

2023-07-04 00:04 UTC, Roswell468 approved these changes

2023-07-04 00:05 UTC, merged