Create Reto #0 - C++
mouredev/retos-programacion-2023 pull request #43
Opened 2022-12-27 15:53 UTC by jubach2020

2022-12-27 16:11 UTC, jubach2020 reviewed
.

2022-12-27 16:44 UTC, lombervid commented
Hola.

Tu archivo debería de estar dentro de una carpeta (con el nombre del lenguaje en minúsculas), y el archivo se debe de llamar como tu usario de `Github` y la extensión del lenguaje.

En tu caso sería algo como:
`/Retos/Reto #0 - EL FAMOSO FIZZ BUZZ [Fácil]/cplusplus/jubach2020.cpp`

Aunque no estoy seguro si se manejaría `cplusplus` o `c++` para el nombre de la carptea. Aunque yo me iría más por la primera.

2023-01-02 10:57 UTC, mouredev requested changes
Hola. Revisa las reglas de presentación de ejercicios. Deben encontrarse en una directorio con el nombre del lenguaje y en un fichero con el nombre de tu usuario. 

Vamos a probar con el directorio "c++" ya que ya han creado el llamado "c#" en vez de csharp.

Un saludo.

2023-01-02 11:27 UTC, jubach2020 commented
Creo que ahora esta bien,  anoto las reglas nuevas!!!!

2023-01-02 12:13 UTC, merged