Create destroyWolvesReto#0 - PHP
mouredev/retos-programacion-2023 pull request #5146
Opened 2023-09-28 15:02 UTC by julianpk19961

Created my version of exercice

## Describe tus cambios
***(Opcional)*** *Sobre todo aconsejable si la "Pull Request" se corresponde con una corrección adicional y no con la presentación de un ejercicio.*

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [ ] El título de mi Pull Request sigue este formato: "Reto #[número] - [lenguaje_utilizado]". *(Ej: Reto #0 - Kotlin")*
- [ ] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.kt)*
- [ ] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: Reto #0/kotlin/mouredev.kt)*
- [ ] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [ ] Únicamente he incluído los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/semanales2023](https://retosdeprogramacion.com/semanales2023).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2023-09-28 23:26 UTC, Roswell468 requested changes
Hola! Por favor revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios.

El nombre del fichero debe coincidir con el de tu usuario en GitHub más la extensión del lenguaje. (Ej: mouredev.kt)

Gracias.
Saludos.

2023-09-29 07:53 UTC, kontroldev requested changes
Hola! Por favor revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios.

-El nombre el fichero debe coincidir con el de tu usuario en GitHub más la extensión del lenguaje. (Ej: mouredev.kt)

Gracias.
Saludos.

2023-10-07 16:42 UTC, DayronbermudezG commented
Hola, lo unico que tienes que poner como titulo es:

RETO #1(ejemplo) - LENGUAJE

2023-10-07 17:24 UTC, julianpk19961 commented
Pero no entiendo me dijeron esto arriba:

ola! Por favor revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios.

El nombre del fichero debe coincidir con el de tu usuario en GitHub más la extensión del lenguaje. (Ej: mouredev.kt)

Gracias.
Saludos.



Ahora me dicen:

Hola, lo único que tienes que poner como titulo es:

Reto https://github.com/mouredev/retos-programacion-2023/pull/1(ejemplo) - lenguaje

._. lo siento si no comprendo bien aún

2023-10-07 21:25 UTC, Roswell468 commented
> Pero no entiendo me dijeron esto arriba:
> 
> ola! Por favor revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios.
> 
> El nombre del fichero debe coincidir con el de tu usuario en GitHub más la extensión del lenguaje. (Ej: mouredev.kt)
> 
> Gracias. Saludos.
> 
> Ahora me dicen:
> 
> Hola, lo único que tienes que poner como titulo es:
> 
> Reto #1 - lenguaje
> 
> ._. lo siento si no comprendo bien aún

Hola! Lo que te está diciendo el usuario es que, según las reglas, el titulo de la PR debería ser "**Reto #0 - PHP**", y en esta PR tienes como título "**Create destroyWolvesReto#0 - PHP**".

![image](https://github.com/mouredev/retos-programacion-2023/assets/88008233/8a2a4d23-5c52-4a4f-8070-e5fb230e43a0)

Independientemente de eso, veo que tienes otra PR abierta para la misma solución (https://github.com/mouredev/retos-programacion-2023/pull/5157).

Por favor revisa la otra PR (https://github.com/mouredev/retos-programacion-2023/pull/5157), ya que el nombre del archivo PHP es incorrecto, debe ser tu nombre de usuario de GitHub, es decir **julianpk19961.php** y no **destroywolves.php**.

Esta PR la cerramos para evitar confusiones.

Gracias.
Saludos!

2023-10-07 21:25 UTC, closed without merging