Reto #47 - Dart
mouredev/retos-programacion-2023 pull request #6027
Opened 2023-12-08 21:00 UTC by odmaroliv

## Describe tus cambios
Hice 2 ejercicios, uno en C# y otro en Dart
Gracias

2023-12-09 23:11 UTC, Roswell468 requested changes
Hola! Por favor revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios.

El nombre del fichero debe coincidir con el de tu usuario en GitHub más la extensión del lenguaje. (Ej: mouredev.kt)

Gracias.
Saludos.

2023-12-13 23:41 UTC, odmaroliv commented
Ya corregi el nombre

2023-12-14 22:48 UTC, Roswell468 requested changes
Hola! revisa nuevamente.

- La solución del reto 34 debe estar dentro de la carpeta del lenguaje utilizado (en este caso c#)
- El nombre de la carpeta del lenguaje del reto 47 debe estar en minúsculas (dart).

Gracias.
Saludos.

2024-01-02 11:45 UTC, Roswell468 commented
Hola! De acuerdo al Punto 7 de las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios, cierro la PR por inactividad. 
Puedes enviar de nuevo la corrección cuando quieras.
Saludos.

2024-01-02 11:45 UTC, closed without merging