Reto #1 - C++
mouredev/retos-programacion-2023 pull request #6258
Opened 2024-01-22 19:01 UTC by vjrivmon

## Describe tus cambios
***(Opcional)*** *Sobre todo aconsejable si la "Pull Request" se corresponde con una corrección adicional y no con la presentación de un ejercicio.*

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [ ] El título de mi Pull Request sigue este formato: "Reto #[número] - [lenguaje_utilizado]". *(Ej: Reto #0 - Kotlin")*
- [ ] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.kt)*
- [ ] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: Reto #0/kotlin/mouredev.kt)*
- [ ] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [ ] Únicamente he incluído los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/semanales2023](https://retosdeprogramacion.com/semanales2023).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2024-01-23 08:36 UTC, kontroldev requested changes
NO has añadido el archivo de la solución aportada.

saludos.

2024-02-03 12:03 UTC, vjrivmon commented
Reto#38 - C++ 
He creado la carpeta c++ que aún no existía en ese reto y he hecho el código ahí. Muchas gracias y un saludo!

2024-02-03 12:13 UTC, vjrivmon commented
Reto#1 - El Lenguaje Hacker
Ya he completo correctamente el archivo, espero que ahora esté bien subido

2024-02-04 23:35 UTC, Roswell468 requested changes
Hola, las soluciones están bien, pero incluiste archivos relacionados con el editor de código.
Por favor, elimina estos archivos.
![image](https://github.com/mouredev/retos-programacion-2023/assets/88008233/2dac702c-5b71-4d10-a68d-5172bc033d7b)
Gracias.
Saludos.

2024-02-17 14:12 UTC, Roswell468 commented
Hola,

Se cierra PR por inactividad (Punto 7 de las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar). 
Puedes enviar una nueva cuando quieras. Recuerda revisar reglas y comentarios.

Gracias.
Saludos.

2024-02-17 14:12 UTC, closed without merging

2024-02-19 08:51 UTC, vjrivmon commented
Pensaba que se había enviado la pull request, la interfaz me ha liado un poco la verdad. Lo siento.
________________________________
De: Bruce ***@***.***>
Enviado: sábado, 17 de febrero de 2024 15:12
Para: mouredev/retos-programacion-2023 ***@***.***>
Cc: Vicente Jose Rivas Monferrer ***@***.***>; Author ***@***.***>
Asunto: Re: [mouredev/retos-programacion-2023] Reto #1 - C++ (PR #6258)


Hola,

Se cierra PR por inactividad (Punto 7 de las reglas<https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar>.
Puedes enviar una nueva cuando quieras. Recuerda revisar reglas y comentarios.

Gracias.
Saludos.

—
Reply to this email directly, view it on GitHub<https://github.com/mouredev/retos-programacion-2023/pull/6258#issuecomment-1950219913>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6IARHNTGRPHOMHXH6I377TYUC3GTAVCNFSM6AAAAABCFWZE32VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNJQGIYTSOJRGM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>