Solution Reto #0 Java with Strategy Pattern and Java 8
mouredev/retos-programacion-2023 pull request #63
Opened 2022-12-28 00:21 UTC by codigocaballer

2023-01-02 11:11 UTC, mouredev requested changes
Hola. Gracias por la aportación. Lamentablemente, la corrección debe seguir las reglas que se comentan en el repo y web. Únicamente el fichero de corrección con tu nombre.

Un saludo.

2023-01-03 15:11 UTC, codigocaballer commented
Solución adaptada a las normas lista para mergear:

https://github.com/codigocaballer/retos-programacion-2023/blob/reto0/Retos/Reto%20%230/java/codigocaballer.java

2023-01-04 07:24 UTC, mouredev requested changes
Hola. Has enviado el archivo ejercicio.md. Debes eliminarlo y enviar sólo tu solución.

Un saludo.

2023-01-04 07:31 UTC, codigocaballer commented
Fixeado

2023-01-06 07:14 UTC, mouredev requested changes
Debes revertir los cambios. De esta manera, de aceptar la PR yo también eliminaría el fichero de ejercicio de la rama principal.

Un saludo.

2023-01-07 22:40 UTC, codigocaballer commented
Hecho

2023-01-09 09:05 UTC, merged