Reto #1 - Python
mouredev/retos-programacion-2023 pull request #641
Opened 2023-01-08 00:10 UTC by FundaLab

## Describe tus cambios
***(Opcional)*** *Sobre todo aconsejable si la "Pull Request" se corresponde con una corrección adicional y no con la presentación de un ejercicio.*

## Comprobaciones
Asegúrate de cumplir los siguientes puntos antes de realizar la "Pull Request":

- [ ok ] El título de mi Pull Request sigue este formato: "Reto #[número] - [lenguaje_utilizado]". *(Ej: Reto #0 - Kotlin")*
- [ ok ] El nombre el fichero que se corresponde con el de mi usuario en GitHub más la extensión del lenguaje. *(Ej: mouredev.kt)*
- [ ok ] El fichero de corrección se encuentra dentro del directorio del ejercicio y en una carpeta con el nombre del lenguaje de programación utilizado en minúsculas. *(Ej: Reto #0/kotlin/mouredev.kt)*
- [ ok ] He revisado que el nombre del directorio del lenguaje no es conflictivo:
	- c#, no csharp
	- c++, no cplusplus
	- go, no golang
	- javascript, no js
- [ ok ] Únicamente he incluído los ficheros de ejercicios. No se aceptarán Pull Requests que contengan archivos adicionales asociados a editores de código o semejantes.

## Información

* Tienes toda la información sobre los retos semanales en [retosdeprogramacion.com/semanales2023](https://retosdeprogramacion.com/semanales2023).
* Cada semana se realizará la corrección en directo y publicación de un nuevo reto en [twitch.tv/mouredev](https://twitch.tv/mouredev).
* Recuerda que tienes un grupo de apoyo llamado "reto-semanal" en [Discord](https://discord.gg/mouredev).

2023-01-08 09:23 UTC, mouredev requested changes
Hola. No puedes modificar ficheros creados por mi. Debes revertir los cambios.

Un saludo.

2023-01-12 22:56 UTC, FundaLab commented
Que tal Brais. Que pena, no se nada de GIT. Hice esa PR mirando blog y algunas ayudas de tu canal de discord. No tengo idea cómo revertir cambios. Trataré de indagar en el canal. Saludos y nuevamente disculpas.

2023-01-13 00:30 UTC, Roswell468 commented
Hola @FundaLab , si quieres puedes cerrar esta PR y volver a crear otra solo con el fichero de la solución. Saludos!

2023-01-13 12:05 UTC, FundaLab commented
Gracias . Luego reviso a ver cómo puedo hacer eso.

2023-01-13 12:15 UTC, FundaLab commented
Gracias . Luego reviso a ver cómo puedo hacer eso.

2023-01-13 14:49 UTC, closed without merging

2023-01-13 15:16 UTC, FundaLab commented
Ya la cerré. Ahora a tratar de subirla debidamente