Reto #0 - python
mouredev/retos-programacion-2023 pull request #6467
Opened 2024-04-21 21:49 UTC by AdemarBr

2024-04-23 09:12 UTC, kontroldev requested changes
Hola! Por favor revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios.

-No puedes modificar los ficheros de otros usuarios. Por favor revierte esos cambios.

2024-04-25 14:38 UTC, AdemarBr commented
la modificacion lo hice sobre mi mismo fichero modifique el nombre para que tenga el mismo nombre que tengo en mi github

2024-04-28 14:25 UTC, Roswell468 commented
> la modificacion lo hice sobre mi mismo fichero modifique el nombre para que tenga el mismo nombre que tengo en mi github

Hola, en la PR sigue habiendo dos ejercicios.
![image](https://github.com/mouredev/retos-programacion-2023/assets/88008233/3d51480d-9a97-4235-af4f-099387907e44)
Por favor, revisa nuevamente.
Gracias.
Saludos.

2024-04-28 16:28 UTC, closed without merging

2024-04-28 16:28 UTC, AdemarBr commented
quitandolo