Reto #2 - Python - Rimega
mouredev/retos-programacion-2023 pull request #741
Opened 2023-01-09 22:31 UTC by rimega92

Se añade la respuesta al reto 2
By: Rimega92

2023-01-09 22:45 UTC, joaquin-rivero commented
Buenas! El nombre de usuario es para el archivo, no debe ir en el título de la PR.

2023-01-09 22:56 UTC, rimega92 commented
Se actualiza el título del PR

2023-01-10 00:47 UTC, Roswell468 requested changes
Hola. Revisa las [reglas]( https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios (nombre del directorio y del fichero, sin archivos adicionales). 

Un saludo.

2023-01-10 00:55 UTC, rimega92 commented
> Hola. Revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios (nombre del directorio y del fichero, sin archivos adicionales).
> 
> Un saludo.



Que más quieres que le cambie? Si ya esta cumpliendo

2023-01-10 01:34 UTC, lombervid commented
> > Hola. Revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios (nombre del directorio y del fichero, sin archivos adicionales).
> > Un saludo.
> 
> Que más quieres que le cambie? Si ya esta cumpliendo

Lo que diría es que tu usuario es `rimega92`, y al archivo de llama `rimega.py`. Falta el `92` en el nombre del archivo.

2023-01-10 02:54 UTC, closed without merging