joblari92.kts
mouredev/retos-programacion-2023 pull request #89
Opened 2022-12-28 18:02 UTC by joblari92

2023-01-02 11:36 UTC, mouredev requested changes
Hola. Revisa las [reglas](https://github.com/mouredev/retos-programacion-2023#c%C3%B3mo-puedo-participar) de aportación de ejercicios (nombre del directorio y del fichero).

No se pueden incluir ficheros adicionales.

Un saludo.

2023-01-02 12:41 UTC, joblari92 commented
Algo estoy liando porque en el commit "segundo intento" está bien hecho pero no se como también hice otro a parte con el resto  🤦‍♂️🤦‍♂️

2023-01-02 15:34 UTC, mouredev commented
Recuerda hacer commit y push, ya que aún siguen saliendo los ficheros del IDE.

2023-01-03 07:11 UTC, joblari92 commented
Vale no te mareo más, intentaré hacerlo bien con el próximo reto!

2023-01-03 07:11 UTC, closed without merging